apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: app01
build:
  artifacts:
#  - image: skaffold-buildpacks
  - image: ricc-app01-python-buildpacks
    buildpacks:
      builder: "gcr.io/buildpacks/builder:v1"
      trustBuilder: true
profiles:
- name: gcb
  build:
    googleCloudBuild: {}
