apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: app01
build:
  artifacts:
#  - image: skaff old-buildpa cks # old name
  - image: skaf-app01-python-buildpacks
    #context: my-python-app # not sure what this is for.. this should point to the folder in which the Procfile resides, will default to . I believe
    sync:
      infer:
      - '*.py'
    buildpacks:
      builder: "gcr.io/buildpacks/builder:v1"
      trustBuilder: true
      dependencies:
        ignore: 
          - k8s/**
deploy:
  kustomize: # uses kustomize
    paths: [./k8s/base]
profiles:
  - name: gcb
    build:
      googleCloudBuild: {}
  - name: dev
    deploy:
      kustomize: # uses kustomize
        paths: [./k8s/overlays/dev]
  - name: staging
    deploy:
      kustomize: # uses kustomize
        paths: [./k8s/overlays/staging]
  - name: canary
    deploy:
      kustomize: # uses kustomize
        paths: [./k8s/overlays/canary]
  - name: prod
    deploy:
      kustomize: # uses kustomize
        paths: [./k8s/overlays/prod]

# TODO skaffold profile for solutions. then use with skaffold render or CD release CLI.
#   - name: canary-solution1
#   - name: canary-solution1
  # - name: canary-solution1
  #   deploy:
  #     kustomize: # uses kustomize
  #       paths: [./k8s/overlays/canary]