apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: app01
build:
  artifacts:
  - image: skaffold-buildpacks
#  - image: ricc-app01-python-buildpacks
    #context: my-python-app # not sure what this is for.. 
    # sync:
    #   infer:
    #   - '*.py'
    buildpacks:
      builder: "gcr.io/buildpacks/builder:v1"
#      builder: "gcr.io/buildpacks/builder:654808d82f3ac18d40a5ac189600514ed6947491"
      trustBuilder: true
profiles:
  - name: gcb
    build:
      googleCloudBuild: {}
  - name: dev
#     # activation:
#     # - env: MAGIC_VAR=42
#     #deploy:
#       #kustomize:
#       #  paths: ["k8s/dev-and-staging"] # should be dev but its the same so today ill be lazy...
#   - name: staging
#     # activation:
#     # - env: MAGIC_VAR=43
#     #deploy:
#       #kustomize:
#       #  paths: ["k8s/dev-and-staging"]
#   - name: canary
#     # activation:
#     # - env: MAGIC_VAR=44
#     #deploy:
#       #kustomize:
#       #  paths: ["k8s/canary"]
#   - name: production
#     # activation:
#     # - env: MAGIC_VAR=45
#     #deploy:
#       #kustomize:
#       #  paths: ["k8s/prod"]