apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: app01
build:
  artifacts:
  - image: skaffold-buildpacks
    #context: my-python-app # not sure what this is for.. 
    sync:
      infer:
      - '*.py'
    buildpacks:
      builder: "gcr.io/buildpacks/builder:v1"
      trustBuilder: true
profiles:
  - name: gcb
    build:
      googleCloudBuild: {}
  - name: dev
  - name: staging
  - name: canary
  - name: production