apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../_base
components:
  - ../../../../components/prod/common
replicas: 
  - name: app01-kupython
    count: 9
patchesStrategicMerge:
- increase_replicas.yaml