# # just putting a random YAML to be then integrated with proper image :)
# # copied from https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
# apiVersion: apps/v1
# kind: ReplicaSet
# metadata:
#   name: frontend
#   labels:
#     app: guestbook
#     tier: frontend
#     ricc-env: prod
# spec:
#   # modify replicas according to your case
#   replicas: 8
#   selector:
#     matchLabels:
#       tier: frontend
#   template:
#     metadata:
#       labels:
#         tier: frontend
#     spec:
#       containers:
#       - name: php-redis
#         image: gcr.io/google_samples/gb-frontend:v3