apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
# https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/#setting-cross-cutting-fields
commonLabels:
  is-app-in-production: bingo
  ricc-awesome-selector: canary-or-prod
  ricc-env: canary
commonAnnotations:
  riccNotes: |
    This is common stuff which I include in my CANARY manifests.
    Thanks Daniel and Alex for their help on this!
components:
  - ../base
#################
# Note: THESE are DANGEROUS for my installation as they add plenty of complexity which I need
# to manage on the gcloud side as well, but super cool for the future.
#namespace: my-namespace
#nameSuffix: "-canary"
#################
