---
apiVersion: v1
kind: Service
metadata:
  name: sol0-ilb-${APP_NAME}-prod # was: dmarzi-app-web-02
spec:
  ports:
  - port: 9292
    targetPort: 9292
  selector:
    ricc-awesome-selector: canary-or-prod
---
kind: ServiceExport
apiVersion: net.gke.io/v1
metadata:
  name: sol0-ilb-${APP_NAME}-prod # dmarzi-app-web-02
  namespace: default
