apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
# https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/#setting-cross-cutting-fields
#namespace: my-namespace
#namePrefix: dev-
nameSuffix: "-prod"
commonLabels:
  applicazione-in-produzione: bingo
  ricc-awesome-selector: canary-or-prod
  ricc-env: canary
commonAnnotations:
  riccNotes: |
    This is common stuff which I include in my CANARY manifests.
    Thanks Daniel and Alex for their help on this!

