apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
# https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/#setting-cross-cutting-fields
#namespace: my-namespace
#namePrefix: dev-
nameSuffix: "-prod"
commonLabels:
  app: bingo
commonAnnotations:
  oncallPager: 800-555-1212
  developer: Riccardo Carlesso
  riccNotes: |
    This is common stuff which I include in my PROD manifests.
    Thanks Daniel and Alex for their help on this!
# resources:
# - deployment.yaml


# This only worked with ruby!

# apiVersion: kustomize.config.k8s.io/v1alpha1
# kind: Component
# replicas: 
#   - name: ricc-ruby
#     count: 11 
