apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
#nameSuffix: "-dev"
commonLabels:
  ricc-awesome-selector: dev-or-staging # nothing serious
  ricc-env: dev
commonAnnotations:
  developer: Riccardo Carlesso
  riccNotes: |
    This is common stuff which I include in my DEV manifests.
    Removed -dev suffix which was awesome but created additional complexity
    as my gcloud scripts needed to be aware of it.
components:
  - ../base
#resources:
#   - patch-env-var.yaml
patches:
- patch: |-
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: CLOUD_DEPLOY_TARGET_COMMON
        value: "01 CDev (COMMON Development)"
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: FAVORITE_COLOR_COMMON
        value: '#DB4437'       # Google red or try Blood / sangria.
  target:
    kind: Deployment
    #name: app02-kuruby
