apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
#nameSuffix: "-stag"
commonLabels:
  ricc-awesome-selector: dev-or-staging # nothing serious
  ricc-env: staging
commonAnnotations:
  developer: Riccardo Carlesso
  riccNotes: |
    This is common stuff which I include in my STAGING manifests.
    Testing thje -dev suffix but probably i wanna remove it in a while

