apiVersion: v1
kind: Service
metadata:
  name: app01-web
spec:
  ports:
  - port: 8080
    name: http
  type: LoadBalancer
  selector:
    app: app01-web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app01-web
spec:
  selector:
    matchLabels:
      app: app01-web
  template:
    metadata:
      labels:
        app: app01-web
    spec:
      containers:
      - name: app01-web
        image: skaffold-buildpacks
        env:
          - name: PORT
            value: "8080"
        ports:
          - containerPort: 8080
