apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
# https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/#setting-cross-cutting-fields
#namespace: my-namespace
#nameSuffix: "-prod"
commonLabels:
  applicazione-in-produzione: bingo
  ricc-awesome-selector: canary-or-prod
  ricc-env: prod
commonAnnotations:
  oncallPager: 800-555-1234 (for Production outages only)
  developer: Riccardo Carlesso
  riccNotes: |
    This is common stuff which I include in my PROD manifests.
    Thanks Daniel and Alex for their help on this!
# resources:
# - deployment.yaml
components:
  - ../base


# This only worked with ruby!

# apiVersion: kustomize.config.k8s.io/v1alpha1
# kind: Component
# replicas: 
#   - name: ricc-ruby
#     count: 11 
