# HurricaneAlex: remove Deployments and leave only Services
apiVersion: v1
kind: Service
metadata:
  name: __APPNAME__-sol2-svc-prod # was: svc-prod90 # former svc2-prod90
  annotations:
    networking.gke.io/max-rate-per-endpoint: "10"
    cloud.google.com/neg: '{"exposed_ports": {"8080":{"name": ""}}}'
# Name NEEDS to be autodetected because it needs to be different per cluster.
#    cloud.google.com/neg: '{"exposed_ports": {"8080":{"name": "__APPNAME__-sol2-svc-prod-neg"}}}'
spec:
  selector:
    app: __K8S_APP_SELECTOR__
    # I get ZERO so lets try to make selector laxer
    ricc-env: prod
  ports:
  - port: 8080
    targetPort: 8080
