# HurricaneAlex: remove Deployments and leave only Services
apiVersion: v1
kind: Service
metadata:
  # This needs to be rennamed to `__APPNAME__-sol2-svc-canary`
  name: sol2-__APPNAME__-svc-canary
  annotations:
    networking.gke.io/max-rate-per-endpoint: "10"
    cloud.google.com/neg: '{"exposed_ports": {"8080":{"name": ""}}}'
spec:
  selector:
    app: __K8S_APP_SELECTOR__ # 4. this needs to be like 1/2.
    ricc-env: canary
  ports:
  - port: 8080
    targetPort: 8080
