# kind: Namespace
# apiVersion: v1
# metadata:
#   name: canary
# #  name: app00 # TODO ricc change this
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc2-prod10
  #namespace: canary
spec:
  replicas: 2
  selector:
    matchLabels:
      app: whereami
      version: v2
  template:
    metadata:
      labels:
        app: whereami
        version: v2
    spec:
      containers:
      - name: whereami
        image: gcr.io/google-samples/whereami:v1.2.1
        ports:
          - containerPort: 8080
        env:
        - name: METADATA
          value: "svc2-prod10"
---
apiVersion: v1
kind: Service
metadata:
  name: svc2-prod10
  namespace: canary
  annotations:
    networking.gke.io/max-rate-per-endpoint: "10"
    cloud.google.com/neg: '{"exposed_ports": {"8080":{"name": ""}}}'
spec:
  selector:
    app: whereami
    version: v2
  ports:
  - port: 8080
    targetPort: 8080
