apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: app02
build:
  artifacts:
  - image: ricc-app01-ruby-example   
    context: ruby-app
    sync:
      # Sync app.rb file, being watch with rack-unreloader
      # or add any other rb file to your application
      infer:
      - '*.rb'
# abielski says: This is the issue. Either always pass a profile param to skaffold or change this to point to `./k8s/_base`
deploy:
  kustomize:
    paths: 
    - ./k8s/_base
    - ./k8s/static
profiles:
  - name: dev
    deploy:
      kustomize:
        paths: ["k8s/01dev"] # should be dev but its the same so today ill be lazy...
  - name: staging
    deploy:
      kustomize:
        paths: ["k8s/02staging"]
  - name: canary
    deploy:
      kustomize:
        paths: ["k8s/03canary"]
  - name: production
    deploy:
      kustomize:
        paths: ["k8s/04prod"]