apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: app02
build:
  artifacts:
  - image: ricc-app01-ruby-example   
    context: ruby-app
    sync:
      # Sync app.rb file, being watch with rack-unreloader
      # or add any other rb file to your application
      infer:
      - '*.rb'
deploy:
  kubectl:
    manifests:
    - ./k8s/*yaml
profiles:
  - name: dev
    deploy:
      kustomize:
        paths: ["k8s/01dev"] # should be dev but its the same so today ill be lazy...
  - name: staging
    # deploy:
    #   kustomize:
    #     paths: ["k8s/02staging"]
  - name: canary
    # deploy:
    #   kustomize:
    #     paths: ["k8s/03canary"]
  - name: production
    # deploy:
    #   kustomize:
    #     paths: ["k8s/04production"]