apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
commonLabels:
  application: riccardo-cicd-platinum-path
  github-repo: palladius-colon-cicd-platinum-path
  tier: ricc-frontend-application # => should be in common
  #latest-kustomization-review: '2022-07-12'
commonAnnotations:
  developer: Riccardo Carlesso
