apiVersion: v1
kind: Service
metadata:
  name: webapp01-python # was 'web' and it worked
spec:
  ports:
  - port: 8080
    name: http
  type: LoadBalancer
  selector:
    app: webapp01-python # was 'web' and it worked
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp01-python # was 'web' and it worked
spec:
  selector:
    matchLabels:
      app: webapp01-python # was 'web' and it worked
  template:
    metadata:
      labels:
        app: webapp01-python # was 'web' and it worked
    spec:
      containers:
      - name: webapp01-python # was 'web' and it worked
        #image: ricc-app01-python-buildpacks # skaffold-buildpacks
        image: skaffold-buildpacks
        env:
          - name: PORT
            value: "8080"
          - name: TEST_RICCARDO
            value: |
              I copied and pasted web.yaml inside base and now Im trying to use kustomize instead.
              Not sure if Ill survive but whatever happens we'll see.
          - name: FAVORITE_COLOR
            value: fbf4e2 # NACRE madreperla
          - name: USE_KUSTOMIZE
            value: "true"
          - name: APP_CODE
            value: app01-kustomize
        ports:
          - containerPort: 8080
