apiVersion: v1
kind: Service
metadata:
  name: app01-kupython # was 'web' and it worked
spec:
  ports:
  - port: 8080
    name: http
  type: LoadBalancer
  selector:
    app: app01-kupython # was 'web' and it worked
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app01-kupython # was 'web' and it worked
spec:
  selector:
    matchLabels:
      app: app01-kupython # was 'web' and it worked
  template:
    metadata:
      labels:
        app: app01-kupython # was 'web' and it worked
    spec:
      containers:
      - name: app01-kupython # was 'web' and it worked
        #image: ricc-app01-python-buildpacks # sk affold-bui ldpacks
        image: skaf-app01-python-buildpacks
        env:
          - name: PORT
            value: "8080"
          - name: TEST_RICCARDO
            value: |
              I copied and pasted web.yaml inside base and now Im trying to use kustomize instead.
              Not sure if Ill survive but we'll see.
              Why am I using Kustomize? Thanks for asking. Two reasons mainly:
              1. Learn kustomize
              2. the only legitimate reason is to DRY the 4 dev/stagingca/ary/prod while injecting
                 a slight difference in Canary vs Prod config (9 vs 1 Replicas respectively)
          - name: FAVORITE_COLOR
            value: fbf4e2 # NACRE / madreperla
          - name: USE_KUSTOMIZE
            value: "true"
          - name: APP_CODE
            value: app01-kustomize
        ports:
          - containerPort: 8080
