apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../../../../components/common/canary
replicas: 
  - name: app02-kuruby
    count: 1 
# How do i make the fav color to be yellow?!?
#         - name: FAVORITE_COLOR
#          value: pink # default bkg color, will make it white in prod and yellow in canary.          
patches:
- patch: |-
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: FAVORITE_COLOR
        value: brown
  target:
    kind: Deployment
    name: app02-kuruby