apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../../../../components/common/canary
replicas:
  - name: app02-kuruby
    count: 1
patches:
# TODO(ricc): when you have a minute add patch also here.
- patch: |-
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: FAVORITE_COLOR
        value: brown
  target:
    kind: Deployment
    name: app02-kuruby
