apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../_base
components:
  - ../../../../components/prod/common
replicas: 
  - name: app02-kuruby
    count: 9 # turn it up to
