apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - namespace.yaml
components:
  - ../../../../../components/common/dev
patches:
- patch: |-
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: CLOUD_DEPLOY_TARGET #RICCARDO_KUSTOMIZE_ENV
        value: "01 Dev (Development)"
    # - op: add
    #   path: "/spec/template/spec/containers/0/env/-"
    #   value:
    #     name: FAVORITE_COLOR_DUPE
    #     value: red
  target:
    kind: Deployment
    name: app02-kuruby
# add ...
namespace: cicd-dev
