apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
#nameSuffix: "-stag"
commonLabels:
  ricc-awesome-selector: dev-or-staging # nothing serious
  ricc-env: staging
commonAnnotations:
  developer: Riccardo Carlesso
  riccNotes: |
    This is common stuff which I include in my STAGING manifests.
    Removed the -staging suffix as it added additional unnecessary complexity.
components:
  - ../base
patches:
- patch: |-
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: COMMON_CLOUD_DEPLOY_TARGET
        value: "02 CStaging - COMMON Staging"
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: FAVORITE_COLOR_COMMON
        value: cyan
  target:
    kind: Deployment
