apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cicd-dev # was: development
resources:
  - ../../base
  - namespace.yaml
components:
  - ../../../../../components/common/dev
