apiVersion: v1
kind: Service
metadata:
  name: __PREFIX__-sol1-common-svc
  annotations:
    cloud.google.com/neg: '{"exposed_ports": {"8080":{"name": "__PREFIX__-sol1-common-svc"}}}'
spec:
  selector:
    app: store
  ports:
  - port: 8080
    targetPort: 8080