###########################################################
# This is a K8S template for Solution1 with some variables.
# You cant kubectl apply this or you'll get errors.
#
# Vars:
#  APP_NAME:         __APP_NAME__
#  PREFIX:           __PREFIX__
#  REGION:           __REGION__
#  K8S_APP_SELECTOR: __K8S_APP_SELECTOR__
# .. and so on. in general things with double underscore left and right as Im not a great sedder :)
###########################################################
apiVersion: v1
kind: Service
metadata:
#  name: sol1-__K8S_APP_SELECTOR__-canary
  name: sol1-__PREFIX__-canary
  annotations:
    networking.gke.io/max-rate-per-endpoint: "10"
#    cloud.google.com/neg: '{"exposed_ports": {"8080":{"name": "sol1-__K8S_APP_SELECTOR__-canary-neg"}}}'
    cloud.google.com/neg: '{"exposed_ports": {"8080":{"name": "sol1-__PREFIX__-canary-neg"}}}'
spec:
  selector:
    app: __K8S_APP_SELECTOR__
    ricc-env: canary
  ports:
  - port: 8080
