###########################################################
# This is a K8S template for Solution1 with some variables.
# You cant kubectl apply this or you'll get errors.
#
# Vars:
#  APP_NAME: __APP_NAME__
#  PREFIX:   __PREFIX__
#  REGION:   __REGION__
#
# .. and so on. in general things with double underscore left and right as Im not a great sedder :)
###########################################################
kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1alpha2
metadata:
  name: bifid-external-store
  labels:
    gateway: bifid-external-store-http
spec:
  parentRefs:
  - name: bifid-external-store-http
  hostnames:
  - "bifid-store.example.io"    # kept for easy curl/documented static commands :)
  - "bifid-store.__MY_DOMAIN__" # being changed by script 12 into $MY_DOMAIN.
  rules:
  - backendRefs:
    - name: __PREFIX__sol1-common-svc
      port: 8080
# While this might work, Im gonna remove this.
#      weight: 90
  - matches:
    - path:
        value: /v2
    backendRefs:
    - name: __PREFIX__sol1-v2
      port: 8080
  - matches:
    - path:
        value: /v1
    backendRefs:
    - name: __PREFIX__sol1-v1
      port: 8080
