apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../_base
#components:
#  - ../../../../components/staging/common
replicas: 
  - name: app02-kuruby
    count: 1
patches:
- patch: |-
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: RICCARDO_KUSTOMIZE_ENV
        value: "02 Staging (pls read with French accent)"
  target:
    kind: Deployment
    name: app02-kuruby
