apiVersion: v1
kind: Namespace
metadata:
  annotations:
    developer: Riccardo Carlesso
    oncallPager: 800-555-1234 (for Production outages only)
    riccNotes: |
      This is common stuff which I include in my PROD manifests.
      Thanks Daniel and Alex for their help on this!
  labels:
    application: riccardo-cicd-platinum-path
    applicazione-in-produzione: bingo
    github-repo: palladius-colon-cicd-platinum-path
    ricc-awesome-selector: canary-or-prod
    ricc-env: prod
    tier: ricc-frontend-application
  name: cicd-internal
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    developer: Riccardo Carlesso
    oncallPager: 800-555-1234 (for Production outages only)
    riccNotes: |
      This is common stuff which I include in my PROD manifests.
      Thanks Daniel and Alex for their help on this!
  labels:
    application: riccardo-cicd-platinum-path
    applicazione-in-produzione: bingo
    github-repo: palladius-colon-cicd-platinum-path
    ricc-awesome-selector: canary-or-prod
    ricc-env: prod
    tier: ricc-frontend-application
  name: ricc-ruby-prod
spec:
  ports:
  - port: 9292
    targetPort: 9292
  selector:
    app: ricc-ruby
    application: riccardo-cicd-platinum-path
    applicazione-in-produzione: bingo
    github-repo: palladius-colon-cicd-platinum-path
    ricc-awesome-selector: canary-or-prod
    ricc-env: prod
    tier: ricc-frontend-application
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    developer: Riccardo Carlesso
    oncallPager: 800-555-1234 (for Production outages only)
    riccNotes: |
      This is common stuff which I include in my PROD manifests.
      Thanks Daniel and Alex for their help on this!
  labels:
    application: riccardo-cicd-platinum-path
    applicazione-in-produzione: bingo
    github-repo: palladius-colon-cicd-platinum-path
    ricc-awesome-selector: canary-or-prod
    ricc-env: prod
    tier: ricc-frontend-application
  name: ricc-ruby-prod
spec:
  replicas: 9
  selector:
    matchLabels:
      app: ricc-ruby
      application: riccardo-cicd-platinum-path
      applicazione-in-produzione: bingo
      github-repo: palladius-colon-cicd-platinum-path
      ricc-awesome-selector: canary-or-prod
      ricc-env: prod
      tier: ricc-frontend-application
  template:
    metadata:
      annotations:
        developer: Riccardo Carlesso
        oncallPager: 800-555-1234 (for Production outages only)
        riccNotes: |
          This is common stuff which I include in my PROD manifests.
          Thanks Daniel and Alex for their help on this!
      labels:
        app: ricc-ruby
        application: riccardo-cicd-platinum-path
        applicazione-in-produzione: bingo
        github-repo: palladius-colon-cicd-platinum-path
        ricc-awesome-selector: canary-or-prod
        ricc-env: prod
        tier: ricc-frontend-application
    spec:
      containers:
      - env:
        - name: RACK_ENV
          value: development
        - name: RICCARDO_MESSAGE
          value: Hi! This is the default message if you dont customize to come to
            another target (dev, prod, ..)
        - name: FAVORITE_COLOR
          value: pink
        image: ricc-app01-ruby-example
        name: ricc-ruby
        ports:
        - containerPort: 9292
