apiVersion: v1
kind: Namespace
metadata:
  labels:
    application: riccardo-cicd-platinum-path
    favorite-icecream: pistacchio
    tier: ricc-frontend-application
  name: cicd-internal
---
apiVersion: v1
kind: Service
metadata:
  labels:
    application: riccardo-cicd-platinum-path
    favorite-icecream: pistacchio
    tier: ricc-frontend-application
  name: ricc-ruby
spec:
  ports:
  - port: 9292
    targetPort: 9292
  selector:
    app: ricc-ruby
    application: riccardo-cicd-platinum-path
    favorite-icecream: pistacchio
    tier: ricc-frontend-application
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    application: riccardo-cicd-platinum-path
    favorite-icecream: pistacchio
    tier: ricc-frontend-application
  name: ricc-ruby
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ricc-ruby
      application: riccardo-cicd-platinum-path
      favorite-icecream: pistacchio
      tier: ricc-frontend-application
  template:
    metadata:
      labels:
        app: ricc-ruby
        application: riccardo-cicd-platinum-path
        favorite-icecream: pistacchio
        tier: ricc-frontend-application
    spec:
      containers:
      - env:
        - name: RACK_ENV
          value: development
        - name: RICCARDO_MESSAGE
          value: Hi! This is the default message if you dont customize to come to
            another target (dev, prod, ..)
        - name: FAVORITE_COLOR
          value: pink
        - name: RICCARDO_KUSTOMIZE_ENV
          value: 02 Staging (pls read with French accent)
        image: ricc-app01-ruby-example
        name: ricc-ruby
        ports:
        - containerPort: 9292
