apiVersion: v1
kind: Service
metadata:
  name: app02-kuruby # as in App02, ruby and Kustomized
spec:
  ports:
  - port: 80
    targetPort: 9292
  type: LoadBalancer
  selector:
    app: app02-kuruby
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app02-kuruby
spec:
  selector:
    matchLabels:
      app: app02-kuruby
  template:
    metadata:
      labels:
        app: app02-kuruby
    spec:
      containers:
      - name: app02-kuruby
        image: ricc-app02-kuruby-skaffold    # Dockerized
        ports:
        - containerPort: 9292 # was 80 My pod esxpects traffic here.
        env:
        - name: RACK_ENV
          value: "development"
        - name: APP_NAME
          value: A Wodnerful App in Ruby (app02)
        - name: RICCARDO_MESSAGE
          value: Hi! This is the default message if you dont customize to come to another target (dev, prod, ..)
        - name: FAVORITE_COLOR
          value: pink # default bkg color, will make it white in prod and yellow in canary.

