apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  tier: ricc-frontend-application
resources:
  - app02-kuruby.yaml # Depl+Service
components:
  - ../../../../components/common/base