apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../../../../components/common/prod
replicas:
  - name: app01-kupython
    #count: 9
    count: 4 # moved to 4 - nicer on my cluster :)
