apiVersion: v1
kind: Service
metadata:
  name: store-v1
  annotations:
    networking.gke.io/max-rate-per-endpoint: "10"
    cloud.google.com/neg: '{"exposed_ports": {"8080":{"name": "store-v1-neg"}}}'
spec:
  selector:
    app: store # i need to change
    version: v1
  ports:
  - port: 8080