kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1alpha2
metadata:
  name: sol0-ilb-$APP_NAME-route # was: internal-store-route. Now we have TWO :)
  namespace: default
  labels:
    gateway: sol0-ilb-$APP_NAME-http
spec:
  parentRefs:
  - kind: Gateway
    namespace: default
    name: sol0-ilb-$APP_NAME-http
  hostnames:
  - "sol0-ilb-$APP_NAME.example.io"
  - "sol0-ilb-$APP_NAME.$MY_DOMAIN"
  - "sol0-passepartout.example.io"
  rules:
  - backendRefs:
    # 90% of traffic to store-west-1 ServiceImport
    - name: sol0-ilb-$APP_NAME-canary # dmarzi-app-web-01
      group: net.gke.io
      kind: ServiceImport
      port: 8080
      weight: 90
    # 10% of traffic to store-west-2 ServiceImport
    - name: sol0-ilb-$APP_NAME-prod   # dmarzi-app-web-02
      group: net.gke.io
      kind: ServiceImport
      port: 8080
      weight: 10
