apiVersion: v1
kind: Service
metadata:
  name: webapp01-python
spec:
  ports:
  - port: 8080
    name: http
  type: LoadBalancer
  selector:
    app: webapp01-python
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp01-python
spec:
  selector:
    matchLabels:
      app: webapp01-python
  template:
    metadata:
      labels:
        app: webapp01-python
    spec:
      containers:
      - name: webapp01-python
        image: ricc-app01-python-buildpacks # skaffold-buildpacks
        env:
          - name: PORT
            value: "8080"
          - name: TEST_RICCARDO
            value: Changing just because.
          - name: FAVORITE_COLOR
            value: magenta
        ports:
          - containerPort: 8080
