apiVersion: v1
kind: Service
metadata:
  name: web # was 'webapp01-python' and it worked
spec:
  ports:
  - port: 8080
    name: http
  type: LoadBalancer
  selector:
    app: web 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        #image: ricc-app01-python-buildpacks # skaffold-buildpacks
        image: skaffold-buildpacks
        env:
          - name: PORT
            value: "8080"
          - name: TEST_RICCARDO
            value: |
              Note this code does NOT use Kustomize. If I call it WEB
              it works, but if I rename it  webapp01-python it stops
              working. I know..
          - name: FAVORITE_COLOR
            value: teal
          - name: USE_KUSTOMIZE
            value: "false"
          - name: APP_CODE
            value: app01
          - name: LAST_REVISION
            value: 2022-06-13 and were going for picanha with Eli. 
        ports:
          - containerPort: 8080
