apiVersion: v1
kind: Service
metadata:
  name: app01-python # was 'web' and it worked
spec:
  ports:
  - port: 80
    name: http
  type: LoadBalancer
  selector:
    app: app01-python # was 'web' and it worked
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app01-python # was 'web' and it worked
spec:
  selector:
    matchLabels:
      app: app01-python # was 'web' and it worked
  template:
    metadata:
      labels:
        app: app01-python # was 'web' and it worked
    spec:
      containers:
      - name: app01-python # was 'web' and it worked
        #image: ricc-app01-python-buildpacks # skaffold-buildpacks
        image: skaffold-buildpacks
        env:
          - name: PORT
            value: "8080"
          - name: TEST_RICCARDO
            value: |
              Changing just because. This should NOT appear anymore.
              Note this code does NOT use Kustomize.
              Using app01-python to be obvious.
          - name: FAVORITE_COLOR
            value: teal
          - name: USE_KUSTOMIZE
            value: "false"
          - name: APP_CODE
            value: app01
        ports:
          - containerPort: 8080
